//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wams {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EncodingPresets {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EncodingPresets() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wams.EncodingPresets", typeof(EncodingPresets).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;taskDefinition xmlns=&quot;http://schemas.microsoft.com/iis/media/v4/TM/TaskDefinition#&quot;&gt;
        ///  &lt;name&gt;MP4 to Smooth Streams&lt;/name&gt;
        ///  &lt;id&gt;5e1e1a1c-bba6-11df-8991-0019d1916af0&lt;/id&gt;
        ///  &lt;description xml:lang=&quot;en&quot;&gt;Converts MP4 files encoded with H.264 (AVC) video and AAC-LC audio codecs to Smooth Streams.&lt;/description&gt;
        ///  &lt;inputFolder /&gt;
        ///  &lt;properties namespace=&quot;http://schemas.microsoft.com/iis/media/V4/TM/MP4ToSmooth#&quot; prefix=&quot;mp4&quot;&gt;
        ///    &lt;property name=&quot;keepSourceNames&quot; required=&quot;false&quot; value=&quot;true&quot; helpText=&quot;This p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Mp4ToSmoothStreams {
            get {
                return ResourceManager.GetString("Mp4ToSmoothStreams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;taskDefinition xmlns=&quot;http://schemas.microsoft.com/iis/media/v4/TM/TaskDefinition#&quot;&gt;
        ///    &lt;name&gt;Smooth Streams to Apple HTTP Live Streams&lt;/name&gt;
        ///  &lt;id&gt;A72D7A5D-3022-45f2-89B4-1DDC5457C111&lt;/id&gt;
        ///    &lt;description xml:lang=&quot;en&quot;&gt;Converts on-demand Smooth Streams encoded with H.264 (AVC) video and AAC-LC audio codecs to Apple HTTP Live Streams (MPEG-2 TS) and creates an Apple HTTP Live Streaming playlist (.m3u8) file for the converted presentation.&lt;/description&gt;
        ///    &lt;inputDirectory&gt;&lt;/inputDirectory&gt;
        ///    &lt;out [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SmoothStreamsToAppleHls {
            get {
                return ResourceManager.GetString("SmoothStreamsToAppleHls", resourceCulture);
            }
        }
    }
}
